name: ${project.name}
main: com.biggestnerd.radarjammer.RadarJammer
version: ${project.version}
author: biggestnerd
permissions:
   jammer.bypass:
      description: "Allows you to bypass the radar jammer"
      default: op